import type { DifficultyId } from './coachConfig';

export type Puzzle = {
  id: string;
  title: string;
  fen: string;
  sideToMove: 'w' | 'b';
  difficultyId: DifficultyId;
  theme: string;
  solution: string[];
  hints: string[];
  explanation: string;
};

export const PUZZLES: Puzzle[] = [
  // ── New ─────────────────────────────────────────────────────────────────
  // All validated: solution is legal, position is unambiguous
  {
    id: 'new-back-rank',
    title: 'Back Rank Finish',
    fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'new',
    theme: 'Checkmate pattern',
    solution: ['Re8#'],
    hints: [
      'Look at every square the black king can reach.',
      'A rook on the back rank can seal the king in if the pawns block escape.',
      'Play Re8#. The king has no legal move.',
    ],
    explanation: 'Back rank checkmate: the king is trapped by its own pawns. Slide the rook to the eighth rank for an immediate mate.',
  },
  {
    id: 'new-smothered-queen',
    title: 'Queen Delivers Mate',
    fen: '6k1/5ppp/8/8/3Q4/8/8/6K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'new',
    theme: 'Checkmate pattern',
    solution: ['Qd8#'],
    hints: [
      'The queen is very powerful on open diagonals and files.',
      'Look for a square where the queen gives check with no escape.',
      'Play Qd8#. The black king is stuck in the corner.',
    ],
    explanation: 'A queen on an open board can deliver checkmate from a distance. Find the square that covers all escape routes and gives check.',
  },
  {
    id: 'new-free-piece',
    title: 'Spot the Hanging Piece',
    fen: 'r1b1kb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 0 1',
    sideToMove: 'b',
    difficultyId: 'new',
    theme: 'Piece safety',
    solution: ['Nxe4'],
    hints: [
      'Before your own plan, check whether any opponent piece is undefended.',
      'Count the defenders of the e4 pawn — is it actually protected?',
      'Play Nxe4. The pawn is hanging and you win a free piece.',
    ],
    explanation: 'Always scan for undefended pieces before moving. A pawn left unguarded in the centre is a free gift — take it.',
  },
  {
    id: 'new-rook-edge',
    title: 'Corner the King',
    fen: '7k/6pp/8/8/8/8/8/R6K w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'new',
    theme: 'Checkmate pattern',
    solution: ['Ra8#'],
    hints: [
      'The king is already cornered — what piece can exploit that?',
      'A rook can cover an entire rank from any square on that rank.',
      'Play Ra8#. The edge and corner do the rest.',
    ],
    explanation: 'Rook checkmate on the edge: the king has nowhere to go because the board edge and the rook together seal every square.',
  },
  {
    id: 'new-free-queen',
    title: 'A Free Queen',
    fen: '4k3/8/8/3q4/8/8/8/3RK3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'new',
    theme: 'Piece safety',
    solution: ['Rxd5'],
    hints: [
      'Look at every piece on the board — does anything sit on a square nothing defends?',
      'The black queen on d5 has no defender, and a white piece looks straight at it.',
      'Play Rxd5. The d-file is open, so the rook collects a free queen.',
    ],
    explanation: 'A queen left undefended is the biggest gift in chess. Always scan for hanging pieces before choosing a quiet move — take what is free.',
  },
  {
    id: 'new-bishop-takes-rook',
    title: 'Diagonal Strike',
    fen: '4k3/8/7b/8/8/8/8/2R1K3 b - - 0 1',
    sideToMove: 'b',
    difficultyId: 'new',
    theme: 'Piece safety',
    solution: ['Bxc1'],
    hints: [
      'Trace the bishop\'s long diagonal — does it end on something undefended?',
      'The white rook on c1 has no defenders, and the long dark-square diagonal is wide open.',
      'Play Bxc1. The bishop sweeps across the board to win the rook.',
    ],
    explanation: 'A bishop\'s power comes from its long diagonals. When the diagonal is unblocked and ends on an undefended piece, that piece is yours.',
  },
  {
    id: 'new-pawn-takes-knight',
    title: 'The Pawn Bites',
    fen: '4k3/8/3n4/4P3/8/8/8/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'new',
    theme: 'Piece safety',
    solution: ['exd6'],
    hints: [
      'Even a humble pawn can win a much bigger piece if the piece is unprotected.',
      'The black knight on d6 has no defender. Which pawn can reach it?',
      'Play exd6. The pawn captures diagonally and wins a knight for nothing.',
    ],
    explanation: 'A pawn always captures diagonally. When an enemy piece sits on a pawn\'s capture square and is undefended, the trade is winning even though the pawn is small.',
  },
  {
    id: 'new-knight-takes-bishop',
    title: 'Knight Hop, Free Bishop',
    fen: '4k3/8/8/8/3b4/1N6/8/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'new',
    theme: 'Piece safety',
    solution: ['Nxd4'],
    hints: [
      'A knight reaches squares no other piece can — count the squares two files and one rank away.',
      'The black bishop on d4 is undefended, and a white knight is one hop away.',
      'Play Nxd4. The knight\'s L-shaped jump grabs a free bishop.',
    ],
    explanation: 'Knights move in an L-shape: two squares one way and one square perpendicular. They are perfect for capturing pieces that other units cannot reach.',
  },
  {
    id: 'new-capture-with-check',
    title: 'Take and Check',
    fen: '4k3/8/8/4q3/8/8/4Q3/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'new',
    theme: 'Capture with check',
    solution: ['Qxe5+'],
    hints: [
      'The strongest captures are the ones that also force the opponent to react.',
      'The black queen on e5 is hanging, and capturing it lines up against the black king.',
      'Play Qxe5+. You win the queen and give check at the same time.',
    ],
    explanation: 'A capture that also delivers check is doubly strong: the opponent must address the check instead of recapturing or counter-attacking, so the captured material stays won.',
  },
  {
    id: 'new-promote-pawn',
    title: 'Pawn to Queen',
    fen: '8/4P3/8/8/2k5/8/8/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'new',
    theme: 'Promotion',
    solution: ['e8=Q'],
    hints: [
      'When a pawn reaches the eighth rank it transforms into any piece you choose.',
      'There is no black piece controlling e8 — the pawn can step onto the last rank safely.',
      'Play e8=Q. Pushing the pawn forward turns it into a queen.',
    ],
    explanation: 'Promotion is one of chess\'s biggest power swings: a 1-point pawn becomes a 9-point queen the instant it reaches the eighth rank. Always look for paths to promote in the endgame.',
  },
  {
    id: 'new-queen-mate-afar',
    title: 'Queen From Across',
    fen: '4k3/8/4K3/8/7Q/8/8/8 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'new',
    theme: 'Checkmate pattern',
    solution: ['Qh8#'],
    hints: [
      'When your king stands one square in front of the enemy king, the queen often delivers mate on the back rank.',
      'Find the back-rank square the queen can reach that the enemy king cannot.',
      'Play Qh8#. Your king covers every escape, and the queen seals the back rank.',
    ],
    explanation: 'A king-and-queen mate works because the king takes away the close escape squares while the queen attacks from a safe distance. The mating square is always one your king already controls behind.',
  },
  {
    id: 'new-promote-with-capture',
    title: 'Capture and Crown',
    fen: '3r4/4P3/8/8/8/8/8/k3K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'new',
    theme: 'Promotion',
    solution: ['exd8=Q'],
    hints: [
      'Pawns capture diagonally — and if the capture lands on the eighth rank, they also promote.',
      'The black rook on d8 sits exactly where your pawn can capture diagonally.',
      'Play exd8=Q. You win the rook and gain a queen in the same move.',
    ],
    explanation: 'Capturing a piece while promoting is one of the most rewarding moves in chess. You win the captured piece outright and transform your pawn into a powerful queen.',
  },

  // ── Beginner ────────────────────────────────────────────────────────────
  {
    id: 'beg-knight-fork',
    title: 'Royal Fork',
    fen: 'r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Fork',
    solution: ['Nc7+'],
    hints: [
      'A knight fork hits two pieces at once — find the square that attacks both the king and another valuable piece.',
      'From C 7 a knight reaches both E 8 and A 8 in a single jump — the classic knight L-shape doing double duty.',
      'Play knight to C 7 with check. The king on E 8 must move, and then the rook on A 8 falls.',
    ],
    explanation: 'Nc7+ is a royal-style fork: the knight checks the king on E 8 and attacks the rook on A 8 at the same time. Because the king must address the check first, the rook is lost on the next move. Look for the unique knight square that hits two enemy pieces an L-shape apart.',
  },
  {
    id: 'beg-queen-fork',
    title: 'Queen Forks Royalty',
    fen: '4k3/8/r7/8/8/8/8/3QK3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Fork',
    solution: ['Qe2+'],
    hints: [
      'Look for a queen move that hits two enemy pieces from one square — one along a file or rank and one along a diagonal.',
      'A square one step from your starting position can attack both the king on its file and the rook on a faraway diagonal at the same moment.',
      'Move the queen to E 2 with check. The queen attacks the king on E 8 along the E-file and the rook on A 6 along the E 2 – A 6 diagonal.',
    ],
    explanation: 'Qe2+ is a queen fork. The queen attacks the king on E 8 along the open E-file and the rook on A 6 along the E 2 – A 6 diagonal. Because the king must address the check first, the rook is lost on the next move with Qxa6. Forking on two different lines keeps the queen safe from counter-capture.',
  },
  {
    id: 'beg-take-pinned',
    title: 'Take the Pinned Knight',
    fen: '7k/8/8/4n3/8/8/1B6/7K w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Pin & capture',
    solution: ['Bxe5+'],
    hints: [
      'A pinned piece cannot move without exposing the king to check.',
      'Is the black knight truly able to defend itself?',
      'Play Bxe5+. The bishop pins the knight to the king and takes it for free.',
    ],
    explanation: 'The bishop on b2 sits on the h8–a1 diagonal. The knight on e5 is pinned — moving it would expose the king to check. Capture it for free material.',
  },
  {
    id: 'beg-win-queen',
    title: 'Win the Queen',
    fen: '6k1/5ppp/8/8/3q4/8/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Piece safety',
    solution: ['Rxd4'],
    hints: [
      'Scan the board — is any piece undefended or hanging?',
      'The black queen on d4 has no protection.',
      'Play Rxd4. The queen is free for the taking.',
    ],
    explanation: 'A queen left undefended in the middlegame is often a blunder. Capture it immediately — never let a free queen escape.',
  },
  {
    id: 'beg-bishop-skewer',
    title: 'Bishop Skewer',
    fen: 'r7/8/8/3k4/6B1/8/6K1/8 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Skewer',
    solution: ['Bf3+'],
    hints: [
      'A bishop attacks along diagonals. Look for a diagonal where the enemy king sits in front of another enemy piece.',
      'A skewer is the reverse of a pin: the more valuable piece is checked first and must move, leaving the piece behind it exposed.',
      'Move the bishop to F 3 with check. The diagonal from F 3 hits the king on D 5 first and the rook on A 8 behind it.',
    ],
    explanation: 'Bf3+ is a long-range bishop skewer. The bishop checks the king on D 5 along the F 3 – D 5 diagonal, and the rook on A 8 sits on the same diagonal behind the king. The king must step off the line, after which Bxa8 wins the rook. Skewer = the bigger piece in front, the smaller piece behind.',
  },
  {
    id: 'beg-discover-check',
    title: 'Step Aside, Queen Strikes',
    fen: 'q3k3/8/5R2/3n4/8/8/8/7K b - - 0 1',
    sideToMove: 'b',
    difficultyId: 'beginner',
    theme: 'Discovered check',
    solution: ['Nxf6+'],
    hints: [
      'Look at the long diagonal from your queen — is one of your own pieces sitting in the way?',
      'A discovered check happens when moving one piece uncovers a check from a long-range piece behind it. If the moving piece can also capture something, even better.',
      'Take the rook on F 6 with the knight. The knight captures a rook AND clears the diagonal, so the queen on A 8 checks the white king on H 1.',
    ],
    explanation: 'Nxf6+ is a textbook discovered check. The knight jumps off the A 8 – H 1 diagonal, unmasking the queen which now checks the king from far away. The move also captures a rook for free, because the white king is busy dealing with the check and cannot recapture. Always look for a piece you can move that uncovers a long-range attacker behind it.',
  },

  {
    id: 'beg-remove-defender',
    title: 'Remove the Guard',
    fen: '4k3/5r2/8/8/2b5/3P4/8/5RK1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Removing the defender',
    solution: ['dxc4'],
    hints: [
      'Your rook already lines up on an enemy piece — but something is guarding it. Find a way to remove that guard first.',
      'Removing the defender is a two-step tactic: first capture the piece that protects the target, then take the unguarded target on your next move.',
      'Capture the bishop on C 4 with the pawn. Once the bishop is gone, the rook on F 7 has no protection and you win it next move.',
    ],
    explanation: 'dxc4 eliminates the bishop that guards the rook on f7. The bishop defends f7 along the c4–f7 diagonal — once it is gone, Rxf7 wins a rook with no recapture. Always identify the defender before attacking the target.',
  },
  {
    id: 'beg-rook-mate-2',
    title: 'The Classic Rook Finish',
    fen: '7k/8/6K1/8/8/8/8/R7 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'King and rook mate',
    solution: ['Ra8#'],
    hints: [
      'The enemy king is cornered. Your king is already in the right area — what does the rook need to do?',
      'In a king and rook checkmate the rook sweeps the entire back rank and the king covers the escape squares one row below.',
      'Play rook to A 8. The whole back rank is sealed and your king on G 6 covers G 7 and H 7.',
    ],
    explanation: 'Ra8# is the fundamental king-and-rook checkmate. The rook commands the entire 8th rank, while the white king on g6 controls g7 and h7 — all escape squares are sealed. Learning this pattern is essential for winning rook endgames.',
  },
  {
    id: 'beg-queen-mate-2',
    title: 'King and Queen Work Together',
    fen: '8/8/8/k7/2K5/8/1Q6/8 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'King and queen mate',
    solution: ['Qb5#'],
    hints: [
      'The black king is on the edge and almost out of squares. Look for a queen move that traps it completely.',
      'King and queen checkmate requires the queen to cover all escape squares while the king defends the queen so it cannot be captured.',
      'Move the queen to B 5. The white king on C 4 defends the queen and the black king on A 5 has nowhere to run.',
    ],
    explanation: 'Qb5# is a king-and-queen checkmate. The queen on b5 controls every square around the black king, and the white king on c4 defends the queen so it cannot be taken. The king and queen always work as a pair to deliver this type of mate.',
  },
  {
    id: 'beg-disc-check',
    title: 'Clear the Line',
    fen: 'k1r5/N7/8/8/8/8/8/R3K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Discovered check',
    solution: ['Nxc8+'],
    hints: [
      'Look at the a-file — what is the only piece standing between your rook and the enemy king?',
      'A discovered check happens when you move one piece to reveal an attack from another piece behind it. Can the moving piece also capture something valuable?',
      'Take the rook on C 8 with the knight. That clears the A-file and your rook on A 1 delivers a discovered check to the king on A 8.',
    ],
    explanation: 'Nxc8+ wins the rook AND gives a discovered check in the same move. The knight leaves the a-file, unmasking the rook on a1 which now attacks the king on a8. The opponent must address the check while you keep the captured material.',
  },
  {
    id: 'beg-queen-fork-2',
    title: 'One Move, Two Targets',
    fen: '4k3/8/2n2n2/8/8/8/8/3QK3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Double attack',
    solution: ['Qd6'],
    hints: [
      'Two enemy knights stand on the same rank. The queen is the most versatile attacker — look for one square that aims at both at the same time.',
      'A queen on the 6th rank between the two knights attacks both of them along the rank. Neither knight defends the other and neither can capture the queen.',
      'Slide the queen up the D-file to D 6. From there the queen attacks the knight on C 6 to its left and the knight on F 6 to its right along the 6th rank. Black can only save one.',
    ],
    explanation: 'Qd6 is a double attack on the C 6 and F 6 knights. The queen sits between the two knights on the 6th rank and attacks both along the rank simultaneously. Knights cannot defend each other from those squares and neither can hit back at the queen on D 6, so Black must lose a knight no matter what they play.',
  },
  {
    id: 'beg-pin-rook',
    title: 'Frozen by the File',
    fen: '4k3/8/8/4n3/8/2B5/8/4R1K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Pin & capture',
    solution: ['Bxe5'],
    hints: [
      'Look along the e-file — is there a piece that cannot legally move away because of what stands behind it?',
      'A piece pinned to its own king by a rook on the same file is completely frozen. Find the piece that can safely capture the pinned knight.',
      'Take the knight on E 5 with your bishop. The knight is pinned to the king by the rook and cannot fight back.',
    ],
    explanation: 'The knight on e5 is absolutely pinned: if it moved, the rook on e1 would give check to the king on e8. A pinned piece cannot protect itself — the bishop captures it for free material.',
  },
  {
    id: 'beg-backrank-2',
    title: 'King Helps the Rook',
    fen: '6k1/5p1p/7K/8/8/8/8/1R6 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Back-rank mate',
    solution: ['Rb8#'],
    hints: [
      'The black king is stuck in the corner behind its own pawns. Check whether your king covers the nearby escape squares.',
      'A back-rank checkmate needs the rook to seal the last rank and the king to cover any side escape.',
      'Slide the rook to B 8. The entire back rank is covered and your king on H 6 cuts off G 7 and H 7.',
    ],
    explanation: 'Rb8# is a back-rank checkmate with a twist: the rook seals the whole 8th rank while the white king on h6 personally controls g7 and h7. The own pawns on f7 and h7 trap the black king completely.',
  },
  {
    id: 'beg-rook-skewer',
    title: 'Skewer Along the Rank',
    fen: '8/8/8/2k4r/8/8/8/R3K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Skewer',
    solution: ['Ra5+'],
    hints: [
      'Look at the fifth rank — what happens if your rook slides in and puts heavy pressure on it?',
      'A skewer attacks the most valuable piece first. When that piece moves away, the piece hiding behind it is taken.',
      'Play rook to A 5 with check. The king on C 5 is forced to move, and then you capture the rook on H 5 for free.',
    ],
    explanation: 'Ra5+ skewers the king. A skewer is the reverse of a pin: you attack the more valuable piece first, force it out of the way, and then take the lesser piece sitting behind it.',
  },
  {
    id: 'beg-knight-fork-2',
    title: 'Knight Jumps, King Runs',
    fen: '4r1k1/8/8/3N4/8/8/8/6K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Fork',
    solution: ['Nf6+'],
    hints: [
      'The knight on the fifth rank is close to two valuable pieces — look for a leap that hits both.',
      'A knight fork with check is the most forcing kind: the opponent must deal with the check first and loses the other piece.',
      'Jump the knight to F 6 with check. The king on G 8 must move, and then you win the rook on E 8.',
    ],
    explanation: 'Nf6+ forks king and rook: the knight on f6 gives check to the king on g8 and attacks the rook on e8 at the same moment. Once the king moves, the rook is captured for free.',
  },
  {
    id: 'beg-pawn-fork',
    title: 'Pawn Strikes Twice',
    fen: '4k3/8/2n1n3/8/3P4/8/8/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'beginner',
    theme: 'Fork',
    solution: ['d5'],
    hints: [
      'Look at the pawn in the center — where could it advance to threaten two pieces at once?',
      'A pawn can fork two pieces just like a knight can. Find the advance that attacks both enemy pieces simultaneously.',
      'Push the pawn forward to D 5. It attacks both knights and Black can only save one.',
    ],
    explanation: 'The pawn steps to d5 to fork both black knights: a pawn always captures diagonally, so d5 attacks c6 and e6 at the same time. Black can only move one knight, so the other falls.',
  },

  // ── Intermediate ────────────────────────────────────────────────────────
  {
    id: 'int-pin-queen',
    title: 'Frozen Queen Falls',
    fen: '3k4/8/8/3q4/8/8/6B1/3R2K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Pin & capture',
    solution: ['Bxd5'],
    hints: [
      'A piece pinned along a file cannot legally move — it would expose the king behind it to check.',
      'The black queen sits on the d-file between the king and a rook. A pinned queen is still a queen worth nine points.',
      'Take the queen on D 5 with your bishop. The queen cannot move because of the rook on D 1 behind it.',
    ],
    explanation: 'The rook on d1 absolutely pins the queen on d5 to the king on d8. A pinned piece cannot move, so the bishop walks diagonally to d5 and captures the queen for free — one of the most profitable patterns in chess.',
  },
  {
    id: 'int-zwischenzug',
    title: 'Bishop Seals the Escape',
    fen: '4r1k1/6pp/8/3B4/8/8/6PP/4R1K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Back-rank mate',
    solution: ['Rxe8#'],
    hints: [
      'Look at every square the black king could run to after a rook capture on E 8. Is each one really blocked?',
      'A back-rank mate works when the rook seals the eighth rank and every escape square is covered. Sometimes a long-range piece quietly controls the last flight square.',
      'Take the rook on E 8 with your rook. The king cannot escape to F 7 because your bishop on D 5 covers that diagonal, and the pawns on G 7 and H 7 block the other escape squares.',
    ],
    explanation: 'Rxe8# is a back-rank mate with bishop support. The rook captures and checks along the eighth rank, and Black has no escape: F 8 and H 8 are sealed by the rook, G 7 and H 7 are blocked by Black\'s own pawns, and F 7 is controlled by the bishop on D 5 along the D 5 – F 7 diagonal. Spotting a quiet long-range defender of an escape square is what turns a routine capture into mate.',
  },
  {
    id: 'int-queen-skewer',
    title: 'Queen Skewer on the Rank',
    fen: '8/8/8/2k4r/8/8/8/Q3K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Skewer',
    solution: ['Qa5+'],
    hints: [
      'Both the king and the rook sit on the same rank. A single long-range piece can attack the more valuable one first.',
      'A queen skewer puts the king in check along a rank. When the king steps off, the rook behind it is exposed and lost.',
      'Slide the queen to A 5 with check. The king on C 5 must leave the fifth rank, and then you take the rook on H 5.',
    ],
    explanation: 'Qa5+ is a rank skewer: the queen fires along the fifth rank to check the king. The king is forced to abandon the rook sitting behind it, and Qxh5 follows. The queen is the ideal skewer piece because it travels any distance in one move.',
  },
  {
    id: 'int-bxc6',
    title: 'Bishop Fork — Two Diagonals',
    fen: 'r3k3/2r5/2p5/8/8/8/8/4K2B w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Bishop sacrifice & fork',
    solution: ['Bxc6+'],
    hints: [
      'From c6, a bishop fires along two diagonals. Look at what sits at the end of each diagonal.',
      'A bishop fork attacks the king on one diagonal and a rook on the other. The sacrifice of a pawn can open both lines.',
      'Capture the pawn on C 6 with the bishop. The bishop on C 6 gives check along the E 8 diagonal and attacks the rook on A 8 along the other diagonal.',
    ],
    explanation: 'Bxc6+ sacrifices a bishop for a pawn, but from c6 the bishop simultaneously checks the king on e8 and attacks the rook on a8. The king must address the check, and then the bishop takes the rook — a net gain that more than compensates for the pawn.',
  },
  {
    id: 'int-rook-7th',
    title: 'Rook Storms the Seventh',
    fen: '3k4/ppp5/8/8/8/8/PPP5/3R2K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Rook to 7th rank',
    solution: ['Rd7+'],
    hints: [
      'The seventh rank is the most powerful place for a rook in the endgame. Look for a way to land there immediately.',
      'Forcing the rook onto the seventh rank with check disrupts the king and creates threats on all the undefended pawns.',
      'Drive the rook to D 7 with check. The king is forced to move, and your rook sits behind the enemy pawns harvesting them.',
    ],
    explanation: 'Rd7+ penetrates to the seventh rank with check. The king is driven away and the rook lands right behind the black pawns on a7, b7 and c7. A rook on the seventh rank simultaneously cuts off the king and wins material — the classic endgame technique.',
  },
  {
    id: 'int-queen-rank-fork',
    title: 'Queen on the Long Diagonal',
    fen: 'r7/8/6k1/8/8/8/8/4QK2 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Queen double attack',
    solution: ['Qe4+'],
    hints: [
      'The black king and the black rook are on opposite ends of the long diagonal. One powerful move can attack both from a central square.',
      'A queen placed on the long diagonal attacks both ends at once — check on one side, target on the other — and a rook cannot fight back along a diagonal.',
      'Move the queen to E 4 with check. The queen attacks the king on G 6 along one diagonal and the rook on A 8 along the other, and the rook cannot capture the queen because rooks do not move diagonally.',
    ],
    explanation: 'Qe4+ creates a long-diagonal double attack. The queen checks the king on G 6 along the E 4 – G 6 diagonal and simultaneously aims at the rook on A 8 along the E 4 – A 8 diagonal. The rook cannot defend itself because it cannot move diagonally, and the king must address the check first. After any king move, Qxa8 wins the rook.',
  },
  {
    id: 'int-double-check',
    title: 'Two Checks at Once',
    fen: '8/6k1/4r3/8/3N4/8/8/B6K w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Double check',
    solution: ['Nxe6+'],
    hints: [
      'The knight on d4 can capture something valuable — but also look at what piece it is currently hiding from the enemy king.',
      'A double check occurs when moving one piece exposes a check from another AND the moving piece itself gives check. The king cannot block or capture — it must move.',
      'Take the rook on E 6 with the knight. The knight gives check to G 7, and moving off D 4 reveals the bishop on A 1 also giving check along the diagonal.',
    ],
    explanation: 'Nxe6+ is a double check: the knight on e6 attacks the king on g7, and by leaving d4 the knight also unmasks the bishop on a1 whose diagonal now reaches g7. Against a double check only a king move is legal — you cannot block or capture two checking pieces in one move.',
  },
  {
    id: 'int-knight-fork-queen',
    title: 'Knight Hunts the Queen',
    fen: '3k4/8/8/2q5/3N4/8/8/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Fork',
    solution: ['Ne6+'],
    hints: [
      'The knight is close to both the king and the queen. Find the jump that hits them both.',
      'A knight fork with check is unstoppable: the king must move first, so the queen falls on the next move.',
      'Jump the knight to E 6 with check. The king on D 8 must move, and the queen on C 5 is yours.',
    ],
    explanation: 'Ne6+ forks the king and the queen: from e6 the knight attacks d8 (check) and c5 (queen) at the same time. The king must flee, leaving the queen undefended. A knight fork that includes a check is one of the most reliable ways to win a queen.',
  },
  {
    id: 'int-pin-diagonal',
    title: 'Diagonal Pin, File Strike',
    fen: '6k1/8/4n3/8/2B5/8/8/4R1K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Pin & capture',
    solution: ['Rxe6'],
    hints: [
      'The bishop looks along a diagonal toward the enemy king. Is any piece in between that cannot legally move away?',
      'A piece pinned along a diagonal by a bishop is completely frozen. Can a rook attack that piece from a completely different direction?',
      'Take the knight on E 6 with the rook. The knight is pinned to the king by the bishop on C 4 and cannot defend itself.',
    ],
    explanation: 'The bishop on c4 pins the knight on e6 to the king on g8 along the c4-e6-g8 diagonal — if the knight moved, the bishop would check the king. The rook exploits this by sliding up the e-file to capture the frozen knight for free: a diagonal pin enables a file capture.',
  },
  {
    id: 'int-disc-attack',
    title: 'Step Aside, Open Two Threats',
    fen: '3q2k1/6pp/8/3B4/8/8/5PPP/3R2K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Discovered attack',
    solution: ['Be6+'],
    hints: [
      'Moving the bishop both gives check AND opens up a line for another piece behind it.',
      'A discovered attack creates two threats simultaneously: the bishop checks the king while the rook behind it suddenly attacks the queen on the same file.',
      'Play bishop to E 6 with check. The bishop checks the king on G 8 along the diagonal, and stepping off the D-file unmasks your rook on D 1 attacking the queen on D 8.',
    ],
    explanation: 'Be6+ is a discovered attack with check. The bishop itself checks the king on G 8 along the E 6 – G 8 diagonal, and by stepping off the D-file it uncovers the rook on D 1 attacking the queen on D 8. Black must address the check first — and the queen cannot escape, because after any king move White plays Rxd8 winning the queen. Two threats from one move, one of them forcing.',
  },
  {
    id: 'int-nd5-outpost',
    title: 'Dominant Knight',
    fen: 'r3kb1r/ppbp1ppp/1qn5/4p3/4P3/2NP1N2/PPP2PPP/R1BQKB1R w KQkq - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Outpost & double attack',
    solution: ['Nd5'],
    hints: [
      'Look for a central square where a knight cannot be driven away by pawns and attacks two pieces at once.',
      'The knight can jump to a strong central outpost that attacks both the queen and a minor piece on the seventh rank.',
      'Play knight to D 5. The knight attacks the queen on B 6 and the bishop on C 7 simultaneously, and no enemy pawn can kick it.',
    ],
    explanation: 'Nd5 is a double attack from a perfect outpost. From D 5 the knight forks the queen on B 6 and the bishop on C 7 — both knight-jumps away. The queen must run, after which Nxc7+ wins the bishop with check. A knight on an unkickable central outpost is one of the most powerful long-term assets in the middlegame.',
  },
  {
    id: 'int-nxf7-sac',
    title: 'Knight Sacrifice',
    fen: 'r4rk1/pp2qppp/2n1p3/3pN3/3P4/2P5/PP2QPPP/R4RK1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Piece sacrifice',
    solution: ['Nxf7'],
    hints: [
      'Count what happens after a piece sacrifice on f7 — is there compensation?',
      'Nxf7 attacks the rook on f8 and the queen on e7. Can Black cope with both threats?',
      'Play Nxf7. After Rxf7 Qxe6 you win back more than you gave.',
    ],
    explanation: 'Nxf7 forces Rxf7 (or loses the queen), then Qxe6 picks up the pawn with a strong central queen. Sacrifice puzzles require calculating at least two moves ahead.',
  },
  {
    id: 'int-strategic-pin',
    title: 'Pin the Defender',
    fen: 'r1bqk2r/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQ1RK1 w kq - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Strategic pin',
    solution: ['Bg5'],
    hints: [
      'Development that creates immediate pressure is better than passive development.',
      'Can you pin a piece that defends a key central pawn or squares near the king?',
      'Play Bg5. The bishop pins the knight on f6, creating lasting pressure on the position.',
    ],
    explanation: 'Bg5 develops the bishop while pinning the knight that defends the e5 pawn and the kingside. The opponent must solve the pin while you improve other pieces.',
  },
  {
    id: 'int-pawn-break',
    title: 'Pawn Breakthrough',
    fen: '8/2p1kp2/1p4p1/1P1K1P2/8/8/8/8 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Pawn break',
    solution: ['f6+'],
    hints: [
      'In pawn endgames, creating a passed pawn is often the key idea.',
      'Which pawn advance forces a favourable exchange and creates an unstoppable passer?',
      'Play f6+. After the king moves, the f-pawn promotes, winning the game.',
    ],
    explanation: 'f6+ forces the king to retreat. The pawn then advances to f7 and promotes. Pawn breaks that create a connected or passed pawn often decide endgames.',
  },
  {
    id: 'int-bxf6-weakening',
    title: 'Weaken the King',
    fen: 'r1bq1rk1/pp3ppp/2nbpn2/3p2B1/3P4/2N1PN2/PP3PPP/R2QK2R w KQ - 0 1',
    sideToMove: 'w',
    difficultyId: 'intermediate',
    theme: 'Structural weakening',
    solution: ['Bxf6'],
    hints: [
      'Consider exchanging a bishop for a knight when it weakens the enemy king\'s pawn cover.',
      'After Bxf6, what is forced and how does Black\'s kingside look?',
      'Play Bxf6. After gxf6 the h7 pawn and f6 pawn are weak, and the king is exposed.',
    ],
    explanation: 'Bxf6 destroys the knight that guards the king. After gxf6 the doubled f-pawns weaken the kingside and open the g-file for a future attack. Material is equal but structural damage is lasting.',
  },

  // ── Advanced ────────────────────────────────────────────────────────────
  {
    id: 'adv-pawn-breakthrough',
    title: 'Unstoppable Passer',
    fen: '8/p3kppp/8/PPP5/8/8/8/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Pawn breakthrough',
    solution: ['b6'],
    hints: [
      'Three pawns against three pawns — calculate which side promotes first.',
      'A pawn sacrifice can open a lane for the other pawns to advance.',
      'Play b6. After axb6 cxb6, the a-pawn runs; after axb6 axb6, your a-pawn is still moving. Work through each branch.',
    ],
    explanation: 'b6! sacrifices a pawn to create an unstoppable passer. All three branches lead to White promoting first. Pawn breakthroughs require exact calculation of every reply.',
  },
  {
    id: 'adv-rook-seventh',
    title: 'Rook to the Seventh',
    fen: '8/6pk/7p/8/8/8/6PP/R5K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Rook endgame',
    solution: ['Ra7'],
    hints: [
      'The seventh rank is the ideal home for a rook in the endgame.',
      'Ra7 cuts off the enemy king and attacks the pawns on g7 and h6.',
      'Play Ra7. The pawns cannot advance and the king cannot help defend them.',
    ],
    explanation: 'Ra7 dominates: it attacks g7 and h7 while cutting off the black king. The pawns are frozen and your own g2 and h2 will advance. Rook activity is the decisive factor in rook endings.',
  },
  {
    id: 'adv-defensive-queen',
    title: 'Active Defence',
    fen: '6k1/5ppp/8/8/8/5Q2/7P/6Kq b - - 0 1',
    sideToMove: 'b',
    difficultyId: 'advanced',
    theme: 'Defense',
    solution: ['Qxf3'],
    hints: [
      'Under pressure, look for active defence before passive waiting moves.',
      'Is there a move that simultaneously eliminates the biggest threat?',
      'Play Qxf3. You remove the dangerous white queen and the position becomes equal.',
    ],
    explanation: 'Strong defence often means taking the initiative. Qxf3 eliminates White\'s most active piece before it causes damage — passive defence would allow White to improve.',
  },
  {
    id: 'adv-opposition-king',
    title: 'Take the Opposition',
    fen: '8/4k3/8/8/4K3/8/8/8 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'King opposition',
    solution: ['Ke5'],
    hints: [
      'In pure king endgames, which king is more active wins.',
      'Direct opposition: kings face each other with exactly one square between them.',
      'Play Ke5. The kings are now in direct opposition and Black must retreat.',
    ],
    explanation: 'Taking the opposition forces the opponent\'s king to give ground. Ke5 places White in direct opposition — Black must step aside, allowing White\'s king to penetrate. This is the cornerstone of all king-and-pawn theory.',
  },
  {
    id: 'adv-zwischenzug',
    title: 'In-Between Move',
    fen: 'r1bq1rk1/pp3ppp/2nbpn2/3p4/3P4/2NBPN2/PP3PPP/R2QK2R w KQ - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Zwischenzug',
    solution: ['Bxh7+'],
    hints: [
      'Before the expected recapture, ask whether there is a forcing move that changes the evaluation.',
      'A check that cannot be ignored is often the zwischenzug — the in-between move.',
      'Play Bxh7+. The king must capture, and after Kxh7 you follow up with a further sequence.',
    ],
    explanation: 'A zwischenzug inserts a forcing move (usually a check) before completing an expected sequence. Bxh7+ gains a pawn and disrupts the king\'s safety before the normal play resumes.',
  },
  {
    id: 'adv-smothered-mate',
    title: 'Smothered by His Own',
    fen: '6rk/6pp/7N/8/8/8/8/6K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Smothered mate',
    solution: ['Nf7#'],
    hints: [
      'The black king sits in the corner — but look at how his own pieces and pawns block every escape square.',
      'A smothered mate is delivered by a knight when the king has no legal squares because all surrounding squares are occupied by friendly pieces.',
      'Jump the knight to F 7. The king on H 8 cannot move because G 7 has a pawn, H 7 has a pawn, and G 8 has the rook.',
    ],
    explanation: 'Nf7# is the classical smothered mate pattern: the knight reaches f7 and checks the king on h8, while every escape square is blocked by Black\'s own pieces — pawns on g7 and h7, rook on g8. No piece can capture or block a knight check, so the king is helpless against this geometry.',
  },
  {
    id: 'adv-queen-skewer-rank',
    title: 'Queen Skewer, Long Diagonal',
    fen: '6kr/8/8/8/8/8/8/Q5K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Skewer',
    solution: ['Qa8+'],
    hints: [
      'There is a tempting capture, but it loses material — look for a quieter move that wins more.',
      'A skewer on the back rank checks the king with a more valuable piece behind it. The king moves and the trailing piece falls.',
      'Slide the queen to A 8 with check. The king on G 8 must step off the eighth rank, and then the rook on H 8 is yours.',
    ],
    explanation: 'Qa8+ is a long-range skewer. Capturing the rook directly with Qxh8+ would lose the queen to Kxh8, but the skewer is decisive: the king is forced to abandon the back rank and Qxh8 wins the rook on the next move. Advanced play means seeing past the obvious capture.',
  },
  {
    id: 'adv-pawn-race',
    title: 'Promote With Tempo',
    fen: '8/Pk6/8/8/8/8/4p1K1/8 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Pawn race',
    solution: ['a8=Q+'],
    hints: [
      'Both sides have pawns racing to promote. Whoever queens with a tempo decides the game.',
      'A promotion that also gives check forces the opponent to respond rather than continue their own race.',
      'Push the pawn to A 8 and promote to a queen with check. The black king must move and then the new queen stops the e-pawn.',
    ],
    explanation: 'a8=Q+ wins the race by gaining a tempo: the new queen checks the king on b7, forcing it to move. While Black handles the check, White returns the queen to stop the black pawn at e2 before it promotes. Pawn races are won by whoever can attach a check to their promotion.',
  },
  {
    id: 'adv-pin-knight-pawn',
    title: 'Pawn Behind the Rook',
    fen: '8/8/5k2/4n3/3P4/8/8/4R1K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Pawn-defended capture',
    solution: ['Rxe5'],
    hints: [
      'The knight looks defended by the king — but check whether the king can actually recapture safely.',
      'A square defended by a pawn becomes off-limits for the enemy king. Use that to capture a piece the king seemingly defends.',
      'Take the knight on E 5 with the rook. The king on F 6 cannot recapture because the pawn on D 4 attacks E 5.',
    ],
    explanation: 'Rxe5 wins a clean piece because the black king cannot recapture: stepping to e5 would walk into check from the pawn on d4. A pawn that controls a key square turns a defended piece into a hanging piece. Advanced players always count attackers, defenders, and X-rays before declaring a piece "defended."',
  },
  {
    id: 'adv-knight-royal-fork',
    title: 'Knight Forks the Royal Couple',
    fen: '8/3q4/8/8/4N3/3k4/8/6K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Royal fork',
    solution: ['Nc5+'],
    hints: [
      'The black king and queen are on the same file, two ranks apart — a familiar knight-fork distance.',
      'A royal fork is the most decisive knight pattern: check the king and attack the queen with one leap.',
      'Jump the knight to C 5. The king on D 3 is in check and the queen on D 7 is attacked at the same time.',
    ],
    explanation: 'Nc5+ is a royal fork — the knight on c5 attacks both the king on d3 (check) and the queen on d7. Because the king must address the check first, the queen is lost on the next move. Spotting that two enemy pieces share a knight-fork geometry is a key advanced skill.',
  },
  {
    id: 'adv-rook-pin-queen-bishop',
    title: 'Bishop Pins, Rook Takes',
    fen: '6k1/8/4q3/8/2B5/8/8/4R1K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Pin & capture',
    solution: ['Rxe6'],
    hints: [
      'The bishop aims at the king along a diagonal. Look at what sits between bishop and king.',
      'A queen pinned by a bishop to the king cannot move without losing the king. A rook on the same file can collect the frozen queen.',
      'Capture the queen on E 6 with the rook. The bishop on C 4 pins the queen against the king on G 8.',
    ],
    explanation: 'The bishop on c4 pins the queen on e6 to the king on g8 along the c4–g8 diagonal. A pinned queen cannot move, so the rook on e1 walks up the e-file and snatches it. Combining a pin on one line with a capture from another is a hallmark of advanced tactics.',
  },
  {
    id: 'adv-mate-rook-king',
    title: 'King Helps the Rook Mate',
    fen: '7k/5K1p/8/8/8/8/8/R7 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'King and rook mate',
    solution: ['Ra8#'],
    hints: [
      'The black king is cornered. Your king on F 7 already controls some critical escape squares.',
      'In a king-and-rook mate the rook seals the back rank while the king cuts off any sideways flight.',
      'Slide the rook to A 8. The eighth rank is sealed, the king on F 7 covers G 7 and G 8, and H 7 is blocked by the pawn.',
    ],
    explanation: 'Ra8# is a king-and-rook checkmate with the white king playing the supporting role. The rook controls the eighth rank, the king on f7 personally guards g7 and g8, and the black h7 pawn blocks the last flight square. Endgame technique rests on recognising these mating nets instantly.',
  },
  {
    id: 'adv-disc-check-pawn',
    title: 'Pawn Step, Bishop Stings',
    fen: '7q/6k1/8/8/3P4/8/8/B5K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Discovered check',
    solution: ['d5+'],
    hints: [
      'The bishop on the long diagonal is currently blocked by one of your own pieces. What happens if that piece steps aside?',
      'A discovered check exposes a long-range attacker. If the line continues past the king, an even bigger piece may be trapped.',
      'Push the pawn to D 5. The bishop on A 1 now sees through to the king on G 7, and after the king moves the queen on H 8 falls.',
    ],
    explanation: 'd5+ is a discovered check from the bishop on a1: moving the pawn clears the long diagonal, attacking the king on g7 and X-raying the queen on h8 behind it. Whichever way the king flees, Bxh8 wins the queen. Pawn-led discovered checks are easy to miss because the moving piece itself looks harmless.',
  },
  {
    id: 'adv-mate-queen-corner',
    title: 'Queen Sweeps the Back Rank',
    fen: 'r6k/6pp/8/3Q4/8/8/5PPP/3B2K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Back-rank mate',
    solution: ['Qxa8#'],
    hints: [
      'The black king sits in the corner with his own pawns blocking every escape. Look for a way to invade the back rank with a single move.',
      'A piece that lands on the eighth rank checks the king — and if the king has no flight squares, the check is mate.',
      'Take the rook on A 8 with the queen. The king on H 8 cannot escape because G 8 is on the eighth rank and G 7 and H 7 are own pawns.',
    ],
    explanation: 'Qxa8# is a one-move back-rank mate: the queen captures the rook and simultaneously checks the king along the eighth rank. The king\'s escape squares g8, g7, and h7 are all blocked — g8 by the queen\'s attack, the others by Black\'s own pawns. Advanced calculation means always scanning the back rank.',
  },
  {
    id: 'adv-pinned-rook-mate',
    title: 'Knight Backs Up the Queen',
    fen: '4k3/4r3/6N1/8/8/8/8/4Q1K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'advanced',
    theme: 'Pin & mate',
    solution: ['Qxe7#'],
    hints: [
      'The queen and rook face off on the e-file, and the black rook is pinned against its king. Find a capture that ends the game.',
      'When a piece is pinned, capturing it can be mate if the king cannot legally recapture. Look for a defender of your queen.',
      'Take the rook on E 7 with the queen. The king on E 8 cannot capture because the knight on G 6 defends the queen.',
    ],
    explanation: 'Qxe7# combines two ideas at once. The rook was pinned to the king, so capturing it is mate because the king cannot legally take the queen — the knight on g6 defends e7 and would deliver check after Kxe7. With every flight square covered by the queen herself, the king has no move.',
  },

  // ── Expert ──────────────────────────────────────────────────────────────
  {
    id: 'exp-underpromote-knight',
    title: 'Queen Is Not Always Best',
    fen: '8/2P1k3/3q4/8/8/8/8/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Underpromotion',
    solution: ['c8=N+'],
    hints: [
      'The pawn is about to promote — but do not automatically pick a queen. Ask what promotion actually achieves the most.',
      'A knight can reach squares no other piece can in a single jump. Could a knight promotion fork two pieces at once?',
      'Promote to a knight on C 8. The knight gives check to the king on E 7 and attacks the queen on D 6 simultaneously.',
    ],
    explanation: 'c8=N+ is the only correct promotion: a queen on c8 cannot reach e7 or d6 in one move, but the knight\'s L-shape attacks both in the same instant — check on the king and a fork of the queen. Expert players always consider all four promotion choices.',
  },
  {
    id: 'exp-deflection',
    title: 'Deflect the Defender',
    fen: '2r3k1/1p3ppp/pN6/3p4/8/P7/1PP2PPP/2R3K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Deflection',
    solution: ['Nxc8'],
    hints: [
      'A deflection removes a defender by capturing it, allowing another threat to land.',
      'The rook on c8 is the only piece guarding critical squares.',
      'Play Nxc8. After Rxc8, your own rook invades with decisive effect.',
    ],
    explanation: 'Nxc8 forces the black rook to leave its defensive post. After Rxc8 Rxc8 the position is won for White. Deflection is a higher-level tactic: you sacrifice a piece to remove a key defender rather than to mate directly.',
  },
  {
    id: 'exp-rook-penetration',
    title: 'Seventh Rank Domination',
    fen: '2r3k1/p4ppp/1p6/3p4/3P4/2R5/P4PPP/6K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Rook endgame',
    solution: ['Rc7'],
    hints: [
      'A rook on the seventh rank simultaneously attacks pawns and restricts the enemy king.',
      'Once the rook reaches c7, can Black generate any counterplay?',
      'Play Rc7. The rook wins pawns on a7, b7, or f7 while the black rook cannot match it.',
    ],
    explanation: 'Rc7 penetrates to the seventh rank with devastating effect: the a7 pawn is immediately under attack and the black king is cut off. Rook endgame technique demands activating the rook as the primary step.',
  },
  {
    id: 'exp-prophylaxis',
    title: 'Stop the Plan',
    fen: 'r2q1rk1/pp2ppbp/2np1np1/3p4/3P4/2NBPN2/PP3PPP/R1BQR1K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Prophylaxis',
    solution: ['h3'],
    hints: [
      'Before you act, ask yourself: what is my opponent\'s next best move and how do I prevent it?',
      'Black\'s knight on f6 wants to jump to g4, creating threats near your king.',
      'Play h3. It stops Ng4 without weakening your position, keeping all options open.',
    ],
    explanation: 'Prophylaxis is the habit of preventing the opponent\'s plan before executing your own. h3 stops Ng4 at no cost. At the expert level, thinking one move ahead for your opponent is as important as thinking ahead for yourself.',
  },
  {
    id: 'exp-fortress-break',
    title: 'Break the Fortress',
    fen: '8/5kpp/5p2/8/8/5PPP/5K2/8 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Zugzwang',
    solution: ['g4'],
    hints: [
      'The position looks symmetrical, but it is White to move and this matters enormously.',
      'A pawn advance on one wing forces a weakness on the other.',
      'Play g4. Black cannot hold the resulting pawn structure — any response leads to a passed pawn.',
    ],
    explanation: 'g4 creates a pawn break that Black cannot adequately meet. After gxh5 gxh5 White has a passed h-pawn; after g5 fxg5 hxg5 White\'s pawns march through. Zugzwang and pawn breaks combine here to decide the endgame.',
  },
  {
    id: 'exp-double-check',
    title: 'Two Checks, One Move',
    fen: 'r3k3/8/4N3/8/8/8/8/4R2K w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Double check',
    solution: ['Nc7+'],
    hints: [
      'The knight stands between your rook and the enemy king. What happens if it leaps to a square that also attacks the king?',
      'A double check forces the king to move because both checks cannot be answered in one move — you cannot block or capture two attackers at once.',
      'Jump the knight to C 7. It checks the king on E 8 directly, and uncovers the rook on E 1 to give check from the file at the same time.',
    ],
    explanation: 'Nc7+ is a double check. The knight checks the king from c7, and moving off e6 simultaneously unmasks the rook on e1 along the e-file. Against a double check the only legal response is a king move — and after the king flees, Nxa8 wins the rook on the next move.',
  },
  {
    id: 'exp-knight-rook-mate',
    title: 'Knight Locks, Rook Strikes',
    fen: '7k/6R1/5N2/8/8/8/8/6K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Coordinated mate',
    solution: ['Rh7#'],
    hints: [
      'The knight already controls a critical escape square next to the enemy king. Find the rook move that delivers mate while staying defended.',
      'When a rook gives check and is defended by a knight that also covers the only flight square, the king has nowhere to run.',
      'Slide the rook to H 7 with check. The knight on F 6 defends the rook and also covers G 8, so the king on H 8 cannot capture and cannot escape.',
    ],
    explanation: 'Rh7# is a textbook coordinated mate. The rook checks the king and is defended by the knight on f6, so Kxh7 walks into a knight check. The same knight also covers g8, eliminating the only escape square. Two pieces working together create a mating net the king cannot break.',
  },
  {
    id: 'exp-stack-attack',
    title: 'Stacked Heavy Pieces',
    fen: '4r1k1/4qppp/8/8/8/4R3/4Q3/6K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Battery overload',
    solution: ['Rxe7'],
    hints: [
      'Both sides have heavy pieces stacked on the same open file. Count the attackers and defenders carefully before you decide who comes out ahead.',
      'When you have more attackers than the opponent has defenders on a key piece, capturing in the right order wins material.',
      'Take the queen on E 7 with the rook. After the rook is recaptured, your queen captures back and you have won a queen for a rook.',
    ],
    explanation: 'Rxe7 starts a winning exchange on the e-file. Black recaptures with Rxe7, but White answers Qxe7 and emerges with an extra queen for a rook. The key is counting: White has two attackers on e7 (rook and queen) while Black has only one defender (the queen itself). The side with more attackers wins the file.',
  },
  {
    id: 'exp-pin-pawn-mate',
    title: 'The Pinned Pawn Falls',
    fen: 'r3k3/4ppp1/6N1/8/8/8/4Q3/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Pin & mate',
    solution: ['Qxe7#'],
    hints: [
      'The black pawn on E 7 is pinned in front of its king. A pinned pawn cannot capture, so think about who supports the e7 square.',
      'When a piece is pinned and another of your pieces defends the square, capturing on that square is often mate because the king cannot legally take back.',
      'Take the pawn on E 7 with the queen. The knight on G 6 defends the queen, so the king on E 8 cannot capture, and every other escape square is covered.',
    ],
    explanation: 'Qxe7# captures the pinned e7 pawn — pinned because moving would expose the king. The knight on g6 defends the queen, so Kxe7 would be illegal (the king would still be in check from the knight). Every flight square around the king is covered by the queen herself. Pin and support combine for a one-move mate.',
  },
  {
    id: 'exp-queen-takes-rook',
    title: 'Long Diagonal, Long Reach',
    fen: 'r5k1/8/8/8/8/8/8/Q5K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Long-range capture',
    solution: ['Qxa8+'],
    hints: [
      'The black rook is far away but undefended. Look for a long-distance move that grabs material with tempo.',
      'A capture that also gives check forces the opponent to respond, gaining you a free tempo on top of the material.',
      'Take the rook on A 8 with the queen. The capture also delivers check on the king along the eighth rank.',
    ],
    explanation: 'Qxa8+ wins the rook with check. The queen slides along the open a-file, captures the rook, and immediately checks the king from a8. Black has to spend a move dealing with the check, leaving White a full rook ahead with the initiative. Long-range queen moves with check are decisive in simplified positions.',
  },
  {
    id: 'exp-mate-N-blocks',
    title: 'Knight Seals the Door',
    fen: '6k1/6pp/8/6N1/8/8/8/3R2K1 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Back-rank mate',
    solution: ['Rd8#'],
    hints: [
      'The black king is hemmed in by his own pawns on G 7 and H 7. Find the only flight square and check whether one of your pieces controls it.',
      'A rook back-rank check is mate when every escape square is covered. Sometimes a knight provides the critical control.',
      'Slide the rook to D 8 with check. The eighth rank is sealed, the pawns block G 7 and H 7, and the knight on G 5 controls the F 7 escape.',
    ],
    explanation: 'Rd8# is a back-rank mate with knight support. The rook seals the eighth rank, Black\'s own pawns block g7 and h7, and the white knight on g5 controls f7 — the only remaining escape. Spotting that a distant piece quietly covers the last flight square is what separates expert tactical vision from average play.',
  },
  {
    id: 'exp-rook-mate-opposition',
    title: 'Opposition Mate',
    fen: '1k6/8/1K6/8/8/8/8/3R4 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'King and rook mate',
    solution: ['Rd8#'],
    hints: [
      'The black king is on the edge and your king is in direct opposition. Find the rook move that ends the game.',
      'When the kings face each other with one square between them, the rook only needs to deliver check along the back rank to finish the job.',
      'Move the rook to D 8 with check. The eighth rank is sealed, and your king on B 6 covers every square the black king might run to.',
    ],
    explanation: 'Rd8# is the cornerstone king-and-rook mate using opposition. The white king on b6 controls a7, b7, and c7, so the black king on b8 cannot flee sideways. The rook delivers check along the eighth rank and covers a8 and c8. Mastering this pattern is the foundation of all rook endgame technique.',
  },
  {
    id: 'exp-knight-fork-K-R',
    title: 'Knight Outpost Strike',
    fen: 'r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Fork',
    solution: ['Nc7+'],
    hints: [
      'The knight is well-placed in the center. Find the leap that hits both the king and another valuable target.',
      'A knight fork that simultaneously checks the king and attacks a rook always wins material — the king must move first and the rook falls.',
      'Jump the knight to C 7. The king on E 8 is in check, and the rook on A 8 is also attacked by the same knight.',
    ],
    explanation: 'Nc7+ forks king and rook. From c7 the knight attacks both e8 (check) and a8 (rook). The king must address the check, and the rook is lost on the next move. Knight forks involving the king are nearly always decisive because the check is the most forcing kind of attack.',
  },
  {
    id: 'exp-active-king',
    title: 'Walk With the Rook',
    fen: '8/8/5k2/8/2K5/8/8/3R4 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'King activity',
    solution: ['Kd5'],
    hints: [
      'In the endgame the king is a fighting piece. Look for the most active king move that also supports your rook.',
      'Centralizing the king is often the strongest plan in a rook endgame. It restricts the enemy king and prepares to escort your pieces.',
      'Step the king to D 5. It centralizes, eyes the enemy king, and supports a future rook advance.',
    ],
    explanation: 'Kd5 is the strongest move because the king must become an active piece in the endgame. Centralizing increases its scope, prevents Black\'s king from advancing, and prepares to support the rook on either flank. Expert players know that the side with the more active king usually wins simplified endgames.',
  },
  {
    id: 'exp-skewer-h-file',
    title: 'Skewer From the Corner',
    fen: '7r/7k/8/8/8/8/6K1/Q7 w - - 0 1',
    sideToMove: 'w',
    difficultyId: 'expert',
    theme: 'Skewer',
    solution: ['Qh1+'],
    hints: [
      'The black king and rook share a file. Find a way to attack the king with the rook trailing directly behind.',
      'A skewer on the h-file forces the king out of the way and leaves the rook stranded.',
      'Slide the queen all the way to H 1 with check. The king on H 7 must move off the h-file, and then the rook on H 8 is yours.',
    ],
    explanation: 'Qh1+ is a long-range skewer. The queen travels from a1 along the first rank to h1, then attacks up the h-file: king first, rook behind. The king cannot stay and must abandon the rook. Spotting a winning skewer that requires the queen to first reposition across the board is a hallmark of expert calculation.',
  },
];

export function puzzleScore(hintsUsed: number, completed: boolean): number {
  if (!completed) return 0;
  if (hintsUsed <= 0) return 100;
  if (hintsUsed === 1) return 60;
  if (hintsUsed === 2) return 30;
  return 10;
}
